# base
train_type: llm
seed: 0
deterministic: True
model: phi3
model_size: 4b     # valid pattern examples: 10b, 1.2b, 2.8, 5 (you can omit b character)

# data config
data_path: ['data/kopolyglot_easy_v2']
template_dir: [templates/phi3_templates]   # list(directory) or directory, if null, template will be chosen according to the {data_path}/templates

# project config
project: outputs/phi3
name: test

# environment config
device: [0,1,2]
bit: 32
load_unnecessary_half: False    # recommend to set True if you set bit to 16 (4, 8bit model automatically loads neccesaries to 32bit)
half_inference: False

# FSDO training configs
fsdp_train: True
fsdp_hyperparameters:
    cpu_offload: True
    wrap_policy: size_based     # [size_based, transformer_based]
    size_based:
        min_num_params: 100     # integer value
    transformer_based:
        fsdp_layer_cls: null    # List of modules to apply FSDP

# data config
max_length: 512
is_multi_turn: False
add_bos_token_when_response_start: True
add_eos_token_when_response_end: True
data_verbose: False

# tokenizer config (I recommend to double check the tokenizer's special token map)
pad_token_id: null     # [add, null, int] if null, tokenizer pad_token_id will not be overrided
bos_token_id: null    # [add, null, int] if null, tokenizer bos_token_id will not be overrided
eos_token_id: 32007    # [add, null, int] if null, tokenizer eos_token_id will not be overrided
cls_token_id: null    # [add, null, int] if null, tokenizer cls_token_id will not be overrided
sep_token_id: null    # [add, null, int] if null, tokenizer sep_token_id will not be overrided
unk_token_id: null    # [add, null, int] if null, tokenizer unk_token_id will not be overrided

# training config
batch_size: 1
epochs: 300
warmup_epochs: 0
steps: 5000
warmup_steps: 100
optimizer_step_criterion: 'step'   # ['epoch', 'step']
lr0: 5e-4
lrf: 0.001      # last_lr = lr0 * lrf
scheduler_type: 'cosine'   # ['linear', 'cosine']
momentum: 0.9
weight_decay: 0.0
warmup_momentum: 0.8
early_stop_criterion: 50
workers: 0
amp_training: False
ema_updating: False
train_verbose: True
inference_result_verbose: True

# peft
peft_config_path: null # config_lora/llm_phi3_lora_config.yaml   # if False, training without peft

# logging data and metrics
common: ['train_loss', 'validation_loss', 'lr']               # ['train_loss', 'validation_loss', 'lr']
metrics: ['ppl', 'bleu', 'rouge', 'edit_distance', 'meteor']  # ['ppl', 'bleu', 'edit_distance', 'rouge', 'meteor']  # TODO: CIDEr 추가
fast_validation_n: 1                                          # [null, 1, 2, ...], Only the number of data of the set value is evaluated per step
fast_validation_step_interval: 200                            # [null, 1, 2, ...], if null, all validation steps will be executed
validation_step_interval_prop: 0.3                            # setting between 0 and 1 values
tensorboard_logging_interval: 1