# base
train_type: nmt
seed: 0
deterministic: True

# data config
data_path: /home/junmin/nas/members/junmin/Documents/dataset/nmt/all_combined
src_lang_code: 'en'
trg_lang_code: 'ko'

# project config
project: runs/llm
name: llm_test

# environment config
device: [0]
bit: 32
half_inference: False

# data config
max_length: 300
data_verbose: False

# training config
batch_size: 4
epochs: 300
warmup_epochs: 10
steps: 4000
warmup_steps: 100
optimizer_step_criterion: 'epoch'   # ['epoch', 'step']
lr0: 0.0001
lrf: 0.001      # last_lr = lr0 * lrf
scheduler_type: 'cosine'   # ['linear', 'cosine']
momentum: 0.9
weight_decay: 0.0
warmup_momentum: 0.8
early_stop_criterion: 50
workers: 0
amp_training: True
ema_updating: False
train_verbose: True

# peft
peft_config_path: config/nmt_lora_config.yaml   # if False, training without peft

# logging
log_data: ['train_loss', 'validation_loss', 'lr']  # ['train_loss', 'validation_loss', 'lr']